version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.3
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
    restart: always  
    env_file:
      - ./environment/.env
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: always    
    depends_on:
      - elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.3
    container_name: logstash
    ports:
      - 28777:28777
      - 5044:5044
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash:/etc/logstash/conf.d
      - ./logstash/patterns:/opt/logstash/patterns
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
    restart: always  
    depends_on:
      - elasticsearch
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.2.3
    container_name: filebeat
    volumes:
      - ./filebeat/filebeat.yml:/filebeat.yml
      - /var/log:/var/log
    restart: always  
    depends_on:
      - logstash

      