actions:
  1:
    action: delete_indices
    description: >-
       Delete indices older than UNIT_COUNT:15 UNIT:days, or when the space used by elasticsearch is 
       greater than 20 GB . Ignore the error if the filter does not result in an
       actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: True
      disable_action: False
    filters:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 15
      exclude:
    - filtertype: space
      disck_space: 21
      reverse: False
      exclude: